name: Dependabot fetch metadata
on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]'}}
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.PAT_TOKEN }}"
        env:
          JIRA_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT: PGS
          JIRA_ISSUE_TYPE: Incident
          JIRA_ISSUE_LABELS: Dependabot
      - name: test
        run: |
          echo ${{ steps.dependabot-metadata.outputs.updated-dependencies-json }}
          echo ${{ steps.dependabot-metadata.outputs.dependency-names }}
          echo ${{ steps.dependabot-metadata.outputs.dependency-type }}
          echo ${{ steps.dependabot-metadata.outputs.update-type }}
          echo ${{ steps.dependabot-metadata.outputs.alert-state }}
          echo ${{ github.repository }}
          echo ${{ github.triggering_actor }}
          echo ${{ github.event.pull_request.html_url }}
          jira_ticket() {
          cat <<- EOF
            {
           "fields":{
           "project":{
           "key":"PGS"
           },
          "summary":"${{ github.triggering_actor }} alert from ${{ github.repository }}",
          "description":" You can get the details of the alert here ${{ github.event.pull_request.html_url }}",
          "issuetype":{
          "name":"Incident"
          },
          "priority":{
          "name":"Low"
          },
          "labels":[
          "Dependabot"
          ]
          }
          }
          EOF
          }
          curl -sH "Authorization: Bearer ${JIRA_TOKEN}" -X POST --data "$(jira_ticket)" \
                             -H "Content-Type: application/json" https://jira.sixt.com/rest/api/2/issue/
          
        shell: bash
